### ISSUE TITLE
aggregateValues

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/loader#1]
Why is `path` used https://github.com/jonschlinkert/loader/blob/master/lib/utils.js#L199

**Comment by jonschlinkert** [comment]
it's just populating the `path` value if it does't exist, or if the parent object didn't have a main key. yeah that's probably not the most idiomatic place for it, but in that particular spot, when the other conditions fail the value there is usually a filepath or glob pattern.

**Comment by doowb** [comment]
cool. it seemed like it was out of place when everything else was so dynamic in that method.

**Comment by jonschlinkert** [comment]
I think I need to refactor the method in general. like all innocent functions, it started out as a simple, unadulterated utility for picking properties on objects passed on the arguments of a variadic function. then, like a typical programmer, I beat it into submission and made it do things it didn't want to do...  an `if` here, an `else` there, now it sings show tunes and randomly spits out chapters of war and peace... Wait, maybe I do that? The lines are getting blurred...

**Comment by doowb** [comment]
lol... go to bed :grinning: 

I never heard `variadic function` before. I had to look it up.

**Comment by jonschlinkert** [comment]
what!?? lol I guess I tend to spout words you haven't heard before when I need sleep!? lol
