### ISSUE TITLE
Something seems wrong in this method...

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/loader#2]
https://github.com/jonschlinkert/loader/blob/master/index.js#L70-L96

On line 77 it calls `this.findLocals` which has the hard coded index of 2, but `locals` is the 3rd argument in `args`.

On line 83 it calls `this.findOptions` which has the hard coded index of 3, but `options` is the 4th argument in `args`.

I might be missing something, but just wanted to point it out.

**Comment by jonschlinkert** [comment]
isn't `args[3]` the fourth argument?

**Comment by jonschlinkert** [comment]
also: https://github.com/jonschlinkert/loader/blob/master/test/findLocals.js and https://github.com/jonschlinkert/loader/blob/master/test/findOptions.js

**Comment by doowb** [comment]
`args[3]` is the fourth argument, but you're using the `argIndex` in `aggregateValues` as a `1` based index instead of `0` based.

That's weird, cause the tests you point to are using it as a 0 based index, but in some other methods, the `locals` object is the second argument (`args[1]`).

That's why I said I might be missing something.

**Comment by jonschlinkert** [comment]
where am I using as a `1` based index in `aggregateValues`? Not saying I'm not, I just don't remember and don't see it lol

**Comment by doowb** [comment]
In [this if statement](https://github.com/jonschlinkert/loader/blob/master/lib/utils.js#L184-L190):

``` js
  if (argIndex && argIndex === argsLen) {
    var value = args[argIndex - 1]; // <=== if argIndex === 2, then it should get args[1]

    if (isObject(value)) {
      _.extend(o, value);
    }
  }
```

**Comment by doowb** [comment]
I see now... that will only happen if `argIndex === argsLen` and `argIndex > 0`

**Comment by jonschlinkert** [comment]
sorry didn't see this til now
